using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class LoadingSceneManager : MonoBehaviour
{
    [SerializeField]
    Image progressBar;

    [SerializeField]
    Text notice;

    bool IsLoadingDone = false;
    bool IsError = false;

    // Start is called before the first frame update
    void Start()
    {
        if(Application.internetReachability == NetworkReachability.NotReachable){
            notice.text = "ì¸í„°ë„· ì—°ê²°ì„ í™•ì¸í•´ì£¼ì„¸ìš”.";
            notice.gameObject.SetActive(true);
            IsError = true;
            return;
        }
        notice.GetComponent<TextAnimation>().setAni(false);
        StartCoroutine(Load());

    }

    private void Update() {
        #if UNITY_EDITOR
        if(IsLoadingDone && Input.GetMouseButtonDown(0)){
            SceneManager.LoadScene("Main Scene");
        }
        if (IsError && Input.GetMouseButtonDown(0)){
            Debug.Log("ì¢…ë£Œ");
            Application.Quit();
        }

        #endif
        #if UNITY_ANDROID
        if(IsLoadingDone && Input.touchCount > 0){
            SceneManager.LoadScene("Main Scene");
        }
        if (IsError && Input.touchCount > 0){
            Debug.Log("ì¢…ë£Œ");
            Application.Quit();
        }
        #endif
    }

    IEnumerator Load(){
        Debug.Log("ë¡œë”© ì‹œì‘");

        notice.text = "Loading";
        notice.gameObject.SetActive(true);
        // API Load Data
        bool apiLoad = GameObject.Find("APIManager").GetComponent<LoadAPI>().IsSuccesLoadData;
        while(!apiLoad){
            apiLoad = GameObject.Find("APIManager").GetComponent<LoadAPI>().IsSuccesLoadData;
            progressBar.fillAmount = GameObject.Find("APIManager").GetComponent<LoadAPI>().getProgress();
            yield return new WaitForSeconds(0.1f);
        }

        // DONE
        progressBar.fillAmount = 1f;

        // ERROR
        notice.gameObject.SetActive(true);

        if(apiLoad == false){
            notice.text = "ì„œë²„ì™€ ì—°ê²°ì´ í•´ì œë¬ìŠµë‹ˆë‹¤.";
            IsError = true;
        }
        else {
            IsLoadingDone = true;
            notice.text = "í™”ë©´ì„ í„°ì¹˜í•´ì£¼ì„¸ìš”.";
            notice.GetComponent<TextAnimation>().setAni(true);
        }
    }

    IEnumerator LoadScene() {
        yield return null;

        // TODO :  ë¹„ë™ê¸° í†µì‹ 
        AsyncOperation op = SceneManager.LoadSceneAsync("Main Scene");
        op.allowSceneActivation = false;

        float timer = 0.0f;
        while (!op.isDone){
            yield return null;

            timer += Time.deltaTime;
            if (op.progress < 0.9f)            
            {                
                progressBar.fillAmount = Mathf.Lerp(progressBar.fillAmount, op.progress, timer);
                if (progressBar.fillAmount >= op.progress)                
                {                    
                    timer = 0f;                
                }            
                else            
                {                
                    progressBar.fillAmount = Mathf.Lerp(progressBar.fillAmount, 1f, timer);
                }
                if (progressBar.fillAmount == 1.0f)                
                {                    
                    op.allowSceneActivation = true;                    
                    yield break;                
                }           
            }
        }
    }
}

/*
ì”¬ì€ ìŠ¬ë¼ì´ë” ê°’ì´ 99% ì´ìƒì¼ ë–„ ë¶ˆëŸ¬ì˜¬ ê²ƒì´ê¸° ë•Œë¬¸ì— ë¯¸ë¦¬ operation.allowSceneActivation = false; ë¡œ í•´ë‘”ë‹¤.
ì”¬ ì „í™˜ì€ 1 í”„ë ˆì„ë§Œì— ì´ë£¨ì–´ì¡Œë‹¤. ê·¸ë•Œ ê·¸ë•Œ ê²½ìš°ì— ë”°ë¼ ë‹¤ë¥´ê² ì§€ë§Œ ì´ë ‡ê²Œ ì”¬ ì „í™˜ì´ ëˆˆê¹œì§í•  ìƒˆì— ì´ë£¨ì–´ì§€ëŠ” ê²½ìš°ë„ ìˆê³  ì´ëŸ´ ë• ë°”ë¡œ operation.progress ê°’ì´ 0.9 ê°€ ë˜ë²„ë ¸ë‹¤.
ê·¸ë˜ì„œ ì”¬ ì „í™˜ì´ ë¹¨ë¦¬ ì´ë£¨ì–´ì¡Œë‹¤ë©´ while ë¬¸ ë‚´ì˜ if ëŠ” ì‹¤í–‰ ì•ˆë˜ê³  ë°”ë¡œ else ë§Œ ì‹¤í–‰ ë ì§€ë„ ëª¨ë¥¸ë‹¤.
operation.progressëŠ” 0.9 ê°€ ìµœëŒ€ê°’ì¸ ê²ƒì„ í™•ì¸í–ˆë‹¤. ê·¸ëƒ¥ ì”¬ ì „í™˜ì´ ì™„ë£Œë˜ë©´ 0.9 ê°’ì´ ë˜ë‚˜ë³´ë‹¤.
ê·¸ë˜ë„ ìŠ¬ë¼ì´ë”ë¥¼ 90%ì¸ ìƒíƒœì—ì„œ ë©ˆì¶œ ìˆ˜ëŠ” ì—†ìœ¼ë‹ˆ, operation.progressê°€ 0.9 ì´ìƒì¼ ë•Œë¶€ì¸ elseë¬¸ì—ì„œëŠ” ìŠ¬ë¼ì´ë” ê°’ì´ 100%ê°€ ë ë•Œê¹Œì§€ timerë¡œ ë³´ê°„í•´ê°€ë©° ë¶€ë“œëŸ½ê²Œ 100% ë¥¼ í–¥í•´ ìŠ¬ë¼ì´ë” ê°’ì„ ì˜¬ë¦°ë‹¤.
Lerp ë³´ê°„ì„ ì‚¬ìš©í•˜ë©´ ë”± ë–¨ì–´ì§€ê²Œ 1f ê°€ ë˜ê¸°ëŠ” í˜ë“¤ë‹¤. ê·¸ë˜ì„œ ìŠ¬ë¼ì´ë” ê°’ì´ 0.99f ë§Œ ë„˜ê²Œ ë˜ë©´ ë°”ë¡œ ë¡œë”©í•˜ëŠ” ì”¬ì„ í™œì„±í™”ì‹œí‚¤ë„ë¡ í•˜ì˜€ë”°. ì´ë•Œ ë¹„ë¡œì†Œ ì”¬ì„ í™œì„±í™”í•œë‹¤. operation.allowSceneActivation = true;
ì´ ìŠ¤í¬ë¦½íŠ¸ëŠ” ì”¬ ì „í™˜ì´ ì™„ë£Œë˜ë„ ê²Œì„ ì”¬ì—ì„œ ì €ì¥í–ˆë˜ ë‚´ìš© ê·¸ëŒ€ë¡œë¥¼ ë¶ˆëŸ¬ì˜¤ëŠ” ì‘ì—…ì„ í•´ì•¼ í•˜ê¸° ë•Œë¬¸ì— (ì¦‰, ğŸ“œSaveAndLoadì˜ LoadData í•¨ìˆ˜ë¥¼ ì‹¤í–‰í•´ì•¼ í•˜ê¸° ë•Œë¬¸ì—) ì‹±ê¸€í†¤ìœ¼ë¡œ ë§Œë“¤ì—ˆë‹¤. ì”¬ì´ ì „í™˜ë˜ë„ íŒŒê´´ë˜ì§€ ì•Šê³  ì „í™˜ëœ ê²Œì„ ì”¬ì—ì„œ theSaveAndLoad.LoadData();ë¥¼ ì‹¤í–‰í•´ì•¼ í•¨.
*/
